{
 "title": "Device Health",
 "tags": [ "Arista" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "device",
    "query": "SHOW TAG VALUES WITH KEY=\"source\""
   },
   {
    "name": "interface",
    "query": {
     "query": "SHOW TAG VALUES FROM \"interfaces-counters\" WITH KEY=\"name\" WHERE \"source\"='${device}'"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "source::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       {
        "params": [
         "Kernel/proc/cpu/utilization/total/util"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source::tag", "operator": "=~", "value": "/^$device$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source::tag", "operator": "=~", "value": "/^$device$/" }
     ]
    }
   ]
  },
  {
   "title": "Bitrate In/Out of ${interface}",
   "type": "timeseries",
   "gridPos": { "h": 19, "w": 17, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name::tag" ], "type": "tag" },
      { "params": [ "source::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "interfaces-counters",
     "select": [
      [
       {
        "params": [
         "interfaces/interface/state/counters/in_octets"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "source::tag", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "name::tag", "operator": "=~", "value": "/^$interface$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Allocation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "Free",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "memory",
     "query": "SELECT last(\"Kernel/proc/meminfo/memFree\") FROM \"memory\" WHERE (\"source\"::tag =~ /^$device$/) AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "Kernel/proc/meminfo/memFree" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source::tag", "operator": "=~", "value": "/^$device$/" }
     ]
    },
    {
     "alias": "Buffers",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "memory",
     "select": [
      [
       { "params": [ "Kernel/proc/meminfo/buffers" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "source::tag", "operator": "=~", "value": "/^$device$/" }
     ]
    },
    {
     "downsampler": "max",
     "expression": "Total",
     "type": "resample",
     "upsampler": "pad",
     "window": "50ms"
    }
   ]
  }
 ]
}