{
 "title": "Arista EOS - Precision Time Protocol (PTP)",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "device",
    "label": "Device",
    "query": {
     "query": "SELECT DISTINCT(\"source\") FROM \"ptp\""
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Grandmaster Clock Identity",
   "type": "state-timeline",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "WITH \n-- 1. Build the Grandmaster Clock Identity as a EUI-64 string\nformatted_data AS (\n  SELECT\n    time,\n    source,\n    concat(\n        lpad(to_hex(\"Sysdb/ptp/status/parentDS/grandmasterIdentity/value/v0\"), 2, '0'), ':',\n        lpad(to_hex(\"Sysdb/ptp/status/parentDS/grandmasterIdentity/value/v1\"), 2, '0'), ':',\n        lpad(to_hex(\"Sysdb/ptp/status/parentDS/grandmasterIdentity/value/v2\"), 2, '0'), ':',\n        lpad(to_hex(\"Sysdb/ptp/status/parentDS/grandmasterIdentity/value/v3\"), 2, '0'), ':',\n        lpad(to_hex(\"Sysdb/ptp/status/parentDS/grandmasterIdentity/value/v4\"), 2, '0'), ':',\n        lpad(to_hex(\"Sysdb/ptp/status/parentDS/grandmasterIdentity/value/v5\"), 2, '0'), ':',\n        lpad(to_hex(\"Sysdb/ptp/status/parentDS/grandmasterIdentity/value/v6\"), 2, '0'), ':',\n        lpad(to_hex(\"Sysdb/ptp/status/parentDS/grandmasterIdentity/value/v7\"), 2, '0')\n    ) AS gm_id\n  FROM \"ptp\"\n  WHERE\n    source IN (${device:singlequote}) -- Only get the devices filtered by the dashboard\n    AND \"Sysdb/ptp/status/parentDS/grandmasterIdentity/value/v0\" IS NOT NULL -- Check if the first octet is not null\n),\n-- The values at \"Sysdb/ptp/status/parentDS/grandmasterIdentity/value\" only change if there is a GM change or if PTP Agent starts\n-- 2. We need to get the latest gm_id BEFORE the dashboard beginning\ninitial_state AS (\n  SELECT\n    -- TRICK : We force time to be the dashboard beginning\n    CAST($__timeFrom AS TIMESTAMP) as time, \n    source,\n    gm_id,\n    -- We order to only keep the most recent values of the past\n    ROW_NUMBER() OVER (PARTITION BY source ORDER BY time DESC) as rn\n  FROM formatted_data\n  WHERE time < $__timeFrom -- We look in the past (before the dashboard time range)\n),\n\n-- 3. We query the data in the dashboard time range\ncurrent_changes AS (\n  SELECT\n    time,\n    source,\n    gm_id\n  FROM formatted_data\n  WHERE time >= $__timeFrom AND time <= $__timeTo\n)\n\n-- 4. We combine both (UNION)\nSELECT time, source, gm_id \nFROM initial_state \nWHERE rn = 1 -- We only keep the latest value of the past\nUNION ALL\nSELECT time, source, gm_id \nFROM current_changes\nORDER BY time ASC;"
    }
   ]
  },
  {
   "title": "Grandmaster Clock Identity",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "WITH all_history AS (\n  SELECT\n    time,\n    source,\n    \"Sysdb/ptp/status/parentDS/grandmasterIdentity/value/v0\" as v0,\n    \"Sysdb/ptp/status/parentDS/grandmasterIdentity/value/v1\" as v1,\n    \"Sysdb/ptp/status/parentDS/grandmasterIdentity/value/v2\" as v2,\n    \"Sysdb/ptp/status/parentDS/grandmasterIdentity/value/v3\" as v3,\n    \"Sysdb/ptp/status/parentDS/grandmasterIdentity/value/v4\" as v4,\n    \"Sysdb/ptp/status/parentDS/grandmasterIdentity/value/v5\" as v5,\n    \"Sysdb/ptp/status/parentDS/grandmasterIdentity/value/v6\" as v6,\n    \"Sysdb/ptp/status/parentDS/grandmasterIdentity/value/v7\" as v7,\n    -- rn=1 is the most recent datapoint received for this device\n    ROW_NUMBER() OVER (PARTITION BY source ORDER BY time DESC) as rn\n  FROM \"ptp\"\n  WHERE\n    \"Sysdb/ptp/status/parentDS/grandmasterIdentity/value/v0\" IS NOT NULL\n    AND source IN (${device:singlequote})\n)\nSELECT\n  source as \"Device\",\n  concat(\n    lpad(to_hex(v0), 2, '0'), ':',\n    lpad(to_hex(v1), 2, '0'), ':',\n    lpad(to_hex(v2), 2, '0'), ':',\n    lpad(to_hex(v3), 2, '0'), ':',\n    lpad(to_hex(v4), 2, '0'), ':',\n    lpad(to_hex(v5), 2, '0'), ':',\n    lpad(to_hex(v6), 2, '0'), ':',\n    lpad(to_hex(v7), 2, '0')\n  ) AS \"Grandmaster Clock Identity\",\n  time as \"Last change\"\nFROM all_history\nWHERE rn = 1 -- We only take the latest value\nORDER BY source ASC;"
    }
   ]
  },
  { "title": "PTP Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "PTP Offset",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\n  time,\n  source,\n  \"Sysdb/ptp/status/currentDS/offsetFromMaster\"\nFROM\n  ptp\nWHERE\n  \"time\" >= $__timeFrom AND \"time\" <= $__timeTo\n  AND\n  \"Sysdb/ptp/status/currentDS/offsetFromMaster\" IS NOT NULL\n  AND \n  \"Sysdb/ptp/status/currentDS/offsetFromMaster\" != 0 -- A perfect (0) offset usually mean the device is not PTP locked\n  AND source IN (${device:singlequote})\nORDER BY time ASC;"
    }
   ]
  },
  {
   "title": "PTP Offset",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "WITH ordered_offsets AS (\n  SELECT\n    time,\n    source,\n    \"Sysdb/ptp/status/currentDS/offsetFromMaster\" AS offset_from_master,\n    -- We order the data by decreasing time for each device\n    ROW_NUMBER() OVER (PARTITION BY source ORDER BY time DESC) as rn\n  FROM \"ptp\"\n  WHERE\n      time >= $__timeFrom AND time <= $__timeTo\n      AND\n      \"Sysdb/ptp/status/currentDS/offsetFromMaster\" IS NOT NULL\n      AND \n      \"Sysdb/ptp/status/currentDS/offsetFromMaster\" != 0 -- A perfect (0) offset usually mean the device is not PTP locked\n      AND source IN (${device:singlequote})\n)\nSELECT\n  time,\n  source,\n  ABS(offset_from_master) AS last_offset_from_master -- We are using the absolute value only here to have nice sorted gauges\nFROM ordered_offsets\n-- We only keep the latest value (most recent)\nWHERE rn = 1\nORDER BY ABS(offset_from_master) DESC;"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 14 },
   "options": {
    "content": "# PTP Offset\n\nThis is the difference between the time reported by the slave clock and the time reported by the master clock that it is attempting to synchronize with."
   }
  },
  {
   "title": "PTP Delay",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\n  time,\n  source,\n  \"Sysdb/ptp/status/currentDS/meanPathDelay\"\nFROM \"ptp\"\nWHERE\n  \"time\" >= $__timeFrom AND \"time\" <= $__timeTo\n  AND\n  \"Sysdb/ptp/status/currentDS/meanPathDelay\" IS NOT NULL\n  AND \n  \"Sysdb/ptp/status/currentDS/meanPathDelay\" != 0 -- A perfect (0) path delay usually mean the device is not PTP locked\n  AND source IN (${device:singlequote})\nORDER BY time ASC;"
    }
   ]
  },
  {
   "title": "PTP Delays",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "WITH ordered_delays AS (\n  SELECT\n    time,\n    source,\n    \"Sysdb/ptp/status/currentDS/meanPathDelay\" AS mean_path_delay,\n    -- We order the data by decreasing time for each device\n    ROW_NUMBER() OVER (PARTITION BY source ORDER BY time DESC) as rn\n  FROM \"ptp\"\n  WHERE\n      time >= $__timeFrom AND time <= $__timeTo\n      AND\n      \"Sysdb/ptp/status/currentDS/meanPathDelay\" IS NOT NULL\n      AND \n      \"Sysdb/ptp/status/currentDS/meanPathDelay\" != 0 -- A perfect (0) path delay usually mean the device is not PTP locked\n      AND source IN (${device:singlequote})\n)\nSELECT\n  time,\n  source,\n  mean_path_delay AS last_mean_path_delay\nFROM ordered_delays\n-- We only keep the latest value (most recent)\nWHERE rn = 1\nORDER BY mean_path_delay DESC;"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 22 },
   "options": {
    "content": "# PTP Delay\n\n This is the time it has taken for a synchronization message to travel from the master clock. It is used by the slave clock to adjust its own time so that it can more accurately synchronize with the master."
   }
  },
  {
   "title": "PTP Jitter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\n  time,\n  source,\n  -- We calculate jitter as the standard deviation of the offset \n  STDDEV(\"Sysdb/ptp/status/currentDS/offsetFromMaster\") OVER (\n    PARTITION BY source\n    ORDER BY time ASC\n    ROWS BETWEEN 59 PRECEDING AND CURRENT ROW\n  ) AS \"Rolling Jitter (1min)\"\nFROM \"ptp\"\nWHERE\n  time >= $__timeFrom AND time <= $__timeTo\n  AND \"Sysdb/ptp/status/currentDS/offsetFromMaster\" IS NOT NULL\n  AND \n  \"Sysdb/ptp/status/currentDS/offsetFromMaster\" != 0 -- A perfect (0) offset usually mean the device is not PTP locked\n  AND source IN (${device:singlequote})\nORDER BY time ASC;"
    }
   ]
  },
  {
   "title": "PTP Jitter",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "WITH rolling_jitters AS (\n  SELECT\n    source,\n    time,\n    -- 1. Calcul de l'écart type sur les 60 dernières valeurs (fenêtre glissante)\n    STDDEV(\"Sysdb/ptp/status/currentDS/offsetFromMaster\") OVER (\n      PARTITION BY source\n      ORDER BY time ASC\n      ROWS BETWEEN 59 PRECEDING AND CURRENT ROW\n    ) AS last_jitter,\n    -- 2. On numérote les lignes pour identifier la plus récente (rn=1)\n    ROW_NUMBER() OVER (PARTITION BY source ORDER BY time DESC) as rn\n  FROM \"ptp\"\n  WHERE\n    -- Optimisation : We only load the latest 15 minutes to calculate latest jitter\n    time >= now() - INTERVAL '15 minutes'\n    AND \"Sysdb/ptp/status/currentDS/offsetFromMaster\" IS NOT NULL\n    AND \n    \"Sysdb/ptp/status/currentDS/offsetFromMaster\" != 0 -- A perfect (0) offset usually mean the device is not PTP locked\n    AND source IN (${device:singlequote})\n)\nSELECT\n  source,\n  last_jitter AS \"Latest Jitter (1min)\"\nFROM rolling_jitters\nWHERE\n  rn = 1 -- On ne garde que la dernière seconde connue\nORDER BY last_jitter DESC;"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 30 },
   "options": {
    "content": "# PTP Jitter\n\n This indicates the variation in the delay between the arrival of consecutive synchronization messages from the master clock. This is calculated using the standard deviation of the PTP offset. A high PTP jitter indicates a high variance in the PTP packets forwarding leading to PTP slaves to calculate a wrong PTP offset."
   }
  },
  {
   "title": "PTP Skew",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 38 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\n  time,\n  source,\n  \"Sysdb/ptp/status/currentDS/skew\"\nFROM \"ptp\"\nWHERE\n  \"time\" >= $__timeFrom AND \"time\" <= $__timeTo\n  AND\n  \"Sysdb/ptp/status/currentDS/skew\" IS NOT NULL\n  AND source IN (${device:singlequote})\nORDER BY time ASC;"
    }
   ]
  },
  {
   "title": "PTP Skew",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "WITH ordered_skews AS (\n  SELECT\n    time,\n    source,\n    \"Sysdb/ptp/status/currentDS/skew\" AS skew,\n    -- We order the data by decreasing time for each device\n    ROW_NUMBER() OVER (PARTITION BY source ORDER BY time DESC) as rn\n  FROM \"ptp\"\n  WHERE\n      time >= $__timeFrom AND time <= $__timeTo\n      AND\n      \"Sysdb/ptp/status/currentDS/skew\" IS NOT NULL\n      AND source IN (${device:singlequote})\n)\nSELECT\n  time,\n  source,\n  skew AS last_skew\nFROM ordered_skews\n-- We only keep the latest value (most recent)\nWHERE rn = 1\nORDER BY skew DESC;"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 38 },
   "options": {
    "content": "# PTP Skew\n\nThis is an estimation of the master clock seconds to the local clock seconds.\nThis is done in software since we lack of synchronization hardware to syntonize. **This value must be close to 1.0.**"
   }
  }
 ]
}