version: '3.7'

volumes:
    influx_data:
      driver: local

services:
  influxdb:
    image: influxdb:2.5
    volumes:
      - influx_data:/var/lib/influxdb2
      - ./influxdb/scripts:/docker-entrypoint-initdb.d
    ports:
      - 8086:8086
    environment:
      - TZ=Europe/Paris
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=arista123
      - DOCKER_INFLUXDB_INIT_ORG=arista
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=arista123
      - DOCKER_INFLUXDB_INIT_BUCKET=default
    healthcheck:
      test: ["CMD", "influx", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - default
      - grafana

  telegraf:
    image: telegraf:latest
    environment:
      HOSTNAME: ceos-telemetry
    links:
      - influxdb
    volumes:
      - ./telegraf:/etc/telegraf
    depends_on:
      - influxdb
    networks:
      - default
      - devices

networks:
  devices:
    name: ceos-telemetry-devices
    external: true
  grafana:
    name: grafana
    external: true